services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=123456
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MARIADB_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100

  glpi:
    build:
      context: ./glpi
      dockerfile: Dockerfile
      # for glpi < 10.0.7 use the dockerfile bellow
      #dockerfile: glpi/Dockerfile-php7
    container_name : glpi
    hostname: glpi
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glpi_www:/var/www/html/glpi
    environment:
      - TIMEZONE=America/sao_paulo
      - VERSION_GLPI=10.0.14
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=glpi_dev
      - DB_USER=root
      - DB_PASSWORD=123456
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    ports:
      - "80:80"

  evolution_api:
    image: atendai/evolution-api:v1.8.5
    container_name: evolution
    hostname: evolution
    restart: always
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - evolution_api/.env
    command: ['node', './dist/src/main.js']
    ports:
      - "8080:8080"

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    hostname: n8n
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false

  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    container_name: typebot
    hostname: typebot
    restart: always
    depends_on:
      - typebot-db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: typebot/.env
    ports:
      - "8081:3000"

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    container_name: bot
    hostname: bot
    restart: always
    env_file: typebot/.env
    ports:
      - "8082:3000"



volumes:
  evolution_instances:
  evolution_store:
  db-data:
  n8n_data:
  glpi_www:

